version: '3.8'
services:
  rpi-dash:
    build: ./server
    container_name: kindleberry
    restart: unless-stopped
    network_mode: host
    privileged: true  # Necess√°rio para ler sensores de hardware no RPi