services:
  rpi-dash:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: kindleberry
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip4:/dev/gpiochip4" # Essencial para o Pi 5
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /sys:/sys:ro
      - ./server/icons:/app/icons