version: "3.8"
services:
  kindleberry:
    image: ghcr.io/zanivann/kindleberry:latest
    container_name: kindleberry
    restart: unless-stopped
    privileged: true
    networks:
      - proxy_network
    ports:
      - "5000:5000"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip4:/dev/gpiochip4"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys:/sys:ro
      # Mapeamos apenas a pasta raiz. 
      # Como os ícones e o config estão dentro de /server no Pi, 
      # eles aparecerão automaticamente em /app no container.
      - /DATA/AppData/kindleberry/server:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kindleberry.rule=Host(`kindle.zanivann.com.br`)"
      - "traefik.http.routers.kindleberry.entrypoints=websecure"
      - "traefik.http.routers.kindleberry.tls=true"
      - "traefik.http.routers.kindleberry.tls.certresolver=myresolver"
      - "traefik.http.services.kindleberry.loadbalancer.server.port=5000"

networks:
  proxy_network:
    external: true